# Generated by Django 4.1.7 on 2023-04-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="format",
            field=models.CharField(
                choices=[("1", "BO1"), ("3", "BO3"), ("5", "BO5")],
                default="3",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[("I", "Incoming"), ("O", "Ongoing"), ("P", "Played")],
                default="I",
                max_length=1,
            ),
        ),
    ]
