# Generated by Django 4.1.7 on 2023-05-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_tournament_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
