# Generated by Django 4.1.7 on 2023-06-30 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams_and_players", "0001_initial"),
        ("matches", "0006_alter_match_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="loser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loser_match",
                to="teams_and_players.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winner_match",
                to="teams_and_players.team",
            ),
        ),
    ]
