# Generated by Django 4.1.7 on 2023-04-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="is_author",
            field=models.BooleanField(default=False),
        ),
    ]
