version: '3.9'

volumes:
  static:
  db-data:

services:
  database:
    image: postgres:14.2
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  dota_website:
    build:
      context: .
    restart: always
    expose:
      - ${DJANGO_PORT}
    volumes:
      - static:/static/
    command: bash -c "
      ./wait-for-postgres.sh database ${POSTGRES_USER} ${POSTGRES_PASSWORD} ${POSTGRES_DB}
      && python manage.py migrate --settings=my_dota.prod_settings
      && python manage.py collectstatic --noinput --settings=my_dota.prod_settings
      && python manage.py test_fill_db --settings=my_dota.prod_settings
      && gunicorn my_dota.wsgi -b 0.0.0.0:${DJANGO_PORT} --workers=1
      "
    depends_on:
      - database
  nginx:
    build: ./nginx
    restart: always
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - static:/etc/nginx/static/
    depends_on:
      - dota_website