# Generated by Django 4.1.7 on 2023-06-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
