# Generated by Django 4.1.7 on 2023-03-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_author_avatar_news_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='main_image',
            field=models.ImageField(default=12, upload_to='news_images'),
            preserve_default=False,
        ),
    ]
