# Generated by Django 4.1.7 on 2023-03-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_news', to='news.author'),
        ),
    ]
