# Generated by Django 4.1.7 on 2023-03-16 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_image_news_id_alter_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_image', to='news.news'),
        ),
    ]
