# Generated by Django 4.1.7 on 2023-08-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("C", "Complete"), ("R", "Running"), ("F", "Failed")],
                        default="R",
                        max_length=1,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
