# Generated by Django 4.1.7 on 2023-08-10 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TaskQueue",
            new_name="QueueTask",
        ),
    ]
