# Generated by Django 4.1.7 on 2023-08-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_rename_taskqueue_queuetask"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuetask",
            name="task_id",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
