# Generated by Django 4.1.7 on 2023-08-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_queuetask_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuetask",
            name="status",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
