# Generated by Django 4.1.7 on 2023-03-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_author_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
