# Generated by Django 4.1.7 on 2023-05-03 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentstage",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament_stages",
                to="tournaments.tournament",
            ),
        ),
    ]
