# Generated by Django 4.1.7 on 2023-05-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_alter_tournamentstage_tournament"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentstage",
            name="stage",
            field=models.CharField(
                choices=[
                    ("GS", "Group Stage"),
                    ("1/8", "1/8"),
                    ("1/4", "1/4"),
                    ("1/2", "1/2"),
                    ("F", "Final"),
                ],
                max_length=20,
            ),
        ),
    ]
