# Generated by Django 4.1.7 on 2023-03-08 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('establish_date', models.DateField()),
                ('all_prize', models.IntegerField()),
                ('all_win_matches', models.IntegerField()),
                ('all_lose_matches', models.IntegerField()),
                ('all_draw_matches', models.IntegerField()),
                ('logo', models.ImageField(upload_to='teams_logos')),
                ('biography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('country', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='players_photos')),
                ('biography', models.TextField()),
                ('all_prize', models.IntegerField()),
                ('all_win_matches', models.IntegerField()),
                ('all_lose_matches', models.IntegerField()),
                ('all_draw_matches', models.IntegerField()),
                ('current_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams_and_players.team')),
            ],
        ),
        migrations.CreateModel(
            name='CareerPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('prize', models.IntegerField()),
                ('win_matches', models.IntegerField()),
                ('lose_matches', models.IntegerField()),
                ('draw_matches', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams_and_players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams_and_players.team')),
            ],
        ),
    ]
