# Generated by Django 4.1.7 on 2023-03-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_and_players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerperiod',
            name='draw_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='careerperiod',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerperiod',
            name='lose_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='careerperiod',
            name='prize',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='careerperiod',
            name='win_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='all_draw_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='all_lose_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='all_prize',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='all_win_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='all_draw_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='all_lose_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='all_prize',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='all_win_matches',
            field=models.IntegerField(default=0),
        ),
    ]
