# Generated by Django 4.1.7 on 2023-03-13 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams_and_players', '0002_alter_careerperiod_draw_matches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='all_draw_matches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='all_lose_matches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='all_prize',
        ),
        migrations.RemoveField(
            model_name='player',
            name='all_win_matches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='all_draw_matches',
        ),
        migrations.RemoveField(
            model_name='team',
            name='all_lose_matches',
        ),
        migrations.RemoveField(
            model_name='team',
            name='all_prize',
        ),
        migrations.RemoveField(
            model_name='team',
            name='all_win_matches',
        ),
        migrations.AlterField(
            model_name='careerperiod',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_career', to='teams_and_players.player'),
        ),
        migrations.AlterField(
            model_name='careerperiod',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_career', to='teams_and_players.team'),
        ),
    ]
