# Generated by Django 4.1.7 on 2023-03-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_and_players', '0003_remove_player_all_draw_matches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='all_draw_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='all_lose_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='all_prize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='all_win_matches',
            field=models.IntegerField(default=0),
        ),
    ]
