# Generated by Django 4.1.7 on 2023-03-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams_and_players', '0004_team_all_draw_matches_team_all_lose_matches_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='all_draw_matches',
            new_name='draw_matches',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='all_lose_matches',
            new_name='lose_matches',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='all_win_matches',
            new_name='win_matches',
        ),
    ]
