# Generated by Django 4.1.7 on 2023-04-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams_and_players', '0005_rename_all_draw_matches_team_draw_matches_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='all_prize',
            new_name='prize',
        ),
    ]
